import { endpoints } from './endpoints'
import { postJson } from './httpClient'

type UnknownRecord = Record<string, unknown>

export const allApi = {
  auth: {
    login: (data: UnknownRecord) => postJson(endpoints.auth.login, data),
    logout: () => postJson(endpoints.auth.logout, {}),
    me: () => postJson(endpoints.auth.me, {}),
    register: (data: UnknownRecord) => postJson(endpoints.auth.register, data),
  },
  user: {
    changeMyPassword: (data: UnknownRecord) => postJson(endpoints.user.changeMyPassword, data),
    deletePreference: (data: UnknownRecord) => postJson(endpoints.user.deletePreference, data),
    preferences: () => postJson(endpoints.user.preferences, {}),
    setPreference: (data: UnknownRecord) => postJson(endpoints.user.setPreference, data),
    updateMe: (data: UnknownRecord) => postJson(endpoints.user.updateMe, data),
    create: (data: UnknownRecord) => postJson(endpoints.user.create, data),
    delete: (data: UnknownRecord) => postJson(endpoints.user.delete, data),
    detail: (data: UnknownRecord) => postJson(endpoints.user.detail, data),
    kycStatus: (data: UnknownRecord) => postJson(endpoints.user.kycStatus, data),
    list: (data: UnknownRecord) => postJson(endpoints.user.list, data),
    riskLevel: (data: UnknownRecord) => postJson(endpoints.user.riskLevel, data),
    status: (data: UnknownRecord) => postJson(endpoints.user.status, data),
    update: (data: UnknownRecord) => postJson(endpoints.user.update, data),
  },
  role: {
    create: (data: UnknownRecord) => postJson(endpoints.role.create, data),
    list: () => postJson(endpoints.role.list, {}),
    configurePermissions: (data: UnknownRecord) => postJson(endpoints.role.configurePermissions, data),
    status: (data: UnknownRecord) => postJson(endpoints.role.status, data),
    update: (data: UnknownRecord) => postJson(endpoints.role.update, data),
    assignUser: (data: UnknownRecord) => postJson(endpoints.role.assignUser, data),
    revokeUser: (data: UnknownRecord) => postJson(endpoints.role.revokeUser, data),
  },
  dataSource: {
    saveHealth: (data: UnknownRecord) => postJson(endpoints.dataSource.saveHealth, data),
    list: (data: UnknownRecord) => postJson(endpoints.dataSource.list, data),
    qualityList: (data: UnknownRecord) => postJson(endpoints.dataSource.qualityList, data),
    saveQuality: (data: UnknownRecord) => postJson(endpoints.dataSource.saveQuality, data),
    save: (data: UnknownRecord) => postJson(endpoints.dataSource.save, data),
  },
  product: {
    saveAttribute: (data: UnknownRecord) => postJson(endpoints.product.saveAttribute, data),
    create: (data: UnknownRecord) => postJson(endpoints.product.create, data),
    delete: (data: UnknownRecord) => postJson(endpoints.product.delete, data),
    saveInvestmentProfile: (data: UnknownRecord) => postJson(endpoints.product.saveInvestmentProfile, data),
    saveQuote: (data: UnknownRecord) => postJson(endpoints.marketQuote.save, data),
    status: (data: UnknownRecord) => postJson(endpoints.product.status, data),
    update: (data: UnknownRecord) => postJson(endpoints.product.update, data),
    detail: (data: UnknownRecord) => postJson(endpoints.product.detail, data),
    list: (data: UnknownRecord) => postJson(endpoints.product.list, data),
    quoteHistory: (data: UnknownRecord) => postJson(endpoints.marketQuote.history, data),
    quoteLatest: (data: UnknownRecord) => postJson(endpoints.marketQuote.latest, data),
  },
  risk: {
    checks: (data: UnknownRecord) => postJson(endpoints.risk.checks, data),
  },
  backtest: {
    detail: (data: UnknownRecord) => postJson(endpoints.backtest.detail, data),
    generateFromPortfolio: (data: UnknownRecord) => postJson(endpoints.backtest.generateFromPortfolio, data),
    list: (data: UnknownRecord) => postJson(endpoints.backtest.list, data),
    save: (data: UnknownRecord) => postJson(endpoints.backtest.save, data),
  },
  feedback: {
    detail: (data: UnknownRecord) => postJson(endpoints.feedback.detail, data),
    list: (data: UnknownRecord) => postJson(endpoints.feedback.list, data),
    save: (data: UnknownRecord) => postJson(endpoints.feedback.save, data),
  },
  promptEvaluation: {
    detail: (data: UnknownRecord) => postJson(endpoints.promptEvaluation.detail, data),
    list: (data: UnknownRecord) => postJson(endpoints.promptEvaluation.list, data),
    save: (data: UnknownRecord) => postJson(endpoints.promptEvaluation.save, data),
  },
  prompt: {
    detail: (data: UnknownRecord) => postJson(endpoints.prompt.detail, data),
    list: (data: UnknownRecord) => postJson(endpoints.prompt.list, data),
    preview: (data: UnknownRecord) => postJson(endpoints.prompt.preview, data),
    save: (data: UnknownRecord) => postJson(endpoints.prompt.save, data),
    status: (data: UnknownRecord) => postJson(endpoints.prompt.status, data),
  },
  aiModel: {
    archive: (data: UnknownRecord) => postJson(endpoints.aiModel.archive, data),
    detail: (data: UnknownRecord) => postJson(endpoints.aiModel.detail, data),
    list: (data: UnknownRecord) => postJson(endpoints.aiModel.list, data),
    save: (data: UnknownRecord) => postJson(endpoints.aiModel.save, data),
    status: (data: UnknownRecord) => postJson(endpoints.aiModel.status, data),
  },
  task: {
    articleRelations: (data: UnknownRecord) => postJson(endpoints.task.articleRelations, data),
    articles: (data: UnknownRecord) => postJson(endpoints.task.articles, data),
    definitions: () => postJson(endpoints.task.definitions, {}),
    saveDefinition: (data: UnknownRecord) => postJson(endpoints.task.saveDefinition, data),
    executions: (data: UnknownRecord) => postJson(endpoints.task.executions, data),
    snapshots: (data: UnknownRecord) => postJson(endpoints.task.snapshots, data),
    trigger: (data: UnknownRecord) => postJson(endpoints.task.trigger, data),
  },
  report: {
    generate: (data: UnknownRecord) => postJson(endpoints.report.generate, data),
    list: (data: UnknownRecord) => postJson(endpoints.report.list, data),
  },
  portfolio: {
    create: (data: UnknownRecord) => postJson(endpoints.portfolio.create, data),
    detail: (data: UnknownRecord) => postJson(endpoints.portfolio.detail, data),
    mine: (data: UnknownRecord) => postJson(endpoints.portfolio.mine, data),
    buy: (data: UnknownRecord) => postJson(endpoints.portfolio.buy, data),
    buyFromReport: (data: UnknownRecord) => postJson(endpoints.portfolio.buyFromReport, data),
    cancelOrder: (data: UnknownRecord) => postJson(endpoints.portfolio.cancelOrder, data),
    orderEvents: (data: UnknownRecord) => postJson(endpoints.portfolio.orderEvents, data),
    sell: (data: UnknownRecord) => postJson(endpoints.portfolio.sell, data),
    performanceCurve: (data: UnknownRecord) => postJson(endpoints.portfolio.performanceCurve, data),
    rebalance: (data: UnknownRecord) => postJson(endpoints.portfolio.rebalance, data),
    refreshValuation: (data: UnknownRecord) => postJson(endpoints.portfolio.refreshValuation, data),
  },
}
