export const endpoints = {
  auth: {
    login: '/api/auth/login',
    logout: '/api/auth/logout',
    me: '/api/auth/me',
    register: '/api/auth/register',
  },
  user: {
    list: '/api/admin/users/list',
    detail: '/api/admin/users/detail',
    create: '/api/admin/users/create',
    update: '/api/admin/users/update',
    delete: '/api/admin/users/delete',
    status: '/api/admin/users/status',
    kycStatus: '/api/admin/users/kyc-status',
    riskLevel: '/api/admin/users/risk-level',
    updateMe: '/api/users/me/update',
    changeMyPassword: '/api/users/me/password',
    preferences: '/api/users/me/preferences/list',
    setPreference: '/api/users/me/preferences/set',
    deletePreference: '/api/users/me/preferences/delete',
  },
  role: {
    list: '/api/admin/roles/list',
    create: '/api/admin/roles/create',
    update: '/api/admin/roles/update',
    status: '/api/admin/roles/status',
    configurePermissions: '/api/admin/roles/permissions/configure',
    assignUser: '/api/admin/roles/users/assign',
    revokeUser: '/api/admin/roles/users/revoke',
  },
  dataSource: {
    list: '/api/admin/data-sources/list',
    save: '/api/admin/data-sources/save',
    discover: '/api/admin/data-sources/discover',
    saveHealth: '/api/admin/data-sources/health/save',
    qualityList: '/api/admin/data-sources/quality/list',
    saveQuality: '/api/admin/data-sources/quality/save',
  },
  task: {
    definitions: '/api/investment/tasks/definitions',
    saveDefinition: '/api/investment/tasks/definitions/save',
    trigger: '/api/investment/tasks/trigger',
    executions: '/api/investment/tasks/executions/list',
    articles: '/api/investment/tasks/articles/list',
    articleRelations: '/api/investment/tasks/article-relations/list',
    snapshots: '/api/investment/tasks/snapshots/list',
  },
  closedLoop: {
    runs: '/api/investment/closed-loop/runs/list',
    detail: '/api/investment/closed-loop/runs/detail',
  },
  product: {
    list: '/api/products/list',
    detail: '/api/products/detail',
    create: '/api/admin/products/create',
    update: '/api/admin/products/update',
    delete: '/api/admin/products/delete',
    status: '/api/admin/products/status',
    saveAttribute: '/api/admin/products/attributes/save',
    saveInvestmentProfile: '/api/admin/products/investment-profile/save',
  },
  marketQuote: {
    history: '/api/products/quotes/history',
    latest: '/api/products/quotes/latest',
    save: '/api/admin/products/quotes/save',
  },
  report: {
    generate: '/api/investment/analysis/generate',
    list: '/api/investment/analysis/reports/list',
  },
  prompt: {
    detail: '/api/ai/prompts/detail',
    list: '/api/ai/prompts/list',
    preview: '/api/ai/prompts/preview',
    save: '/api/ai/prompts/save',
    status: '/api/ai/prompts/status',
  },
  portfolio: {
    create: '/api/mock/portfolios/create',
    detail: '/api/mock/portfolios/detail',
    mine: '/api/mock/portfolios/mine',
    buy: '/api/mock/portfolios/orders/buy',
    buyFromReport: '/api/mock/portfolios/orders/buy-from-report',
    sell: '/api/mock/portfolios/orders/sell',
    cancelOrder: '/api/mock/portfolios/orders/cancel',
    orderEvents: '/api/mock/portfolios/orders/events',
    performanceCurve: '/api/mock/portfolios/performance/curve',
    rebalance: '/api/mock/portfolios/rebalance/execute',
    refreshValuation: '/api/mock/portfolios/valuations/refresh',
  },
  risk: {
    checks: '/api/risk/checks/list',
  },
  backtest: {
    detail: '/api/backtests/detail',
    list: '/api/backtests/list',
    save: '/api/backtests/save',
    generateFromPortfolio: '/api/backtests/generate-from-portfolio',
  },
  feedback: {
    detail: '/api/ai/feedback/detail',
    list: '/api/ai/feedback/list',
    save: '/api/ai/feedback/save',
  },
  promptEvaluation: {
    detail: '/api/ai/prompt-evaluations/detail',
    list: '/api/ai/prompt-evaluations/list',
    save: '/api/ai/prompt-evaluations/save',
  },
  aiModel: {
    archive: '/api/ai/models/archive',
    detail: '/api/ai/models/detail',
    list: '/api/ai/models/list',
    save: '/api/ai/models/save',
    status: '/api/ai/models/status',
  },
  aiSkill: {
    detail: '/api/ai/skills/detail',
    list: '/api/ai/skills/list',
    save: '/api/ai/skills/save',
    status: '/api/ai/skills/status',
  },
  aiModelSkill: {
    byModel: '/api/ai/model-skills/by-model',
    detail: '/api/ai/model-skills/detail',
    list: '/api/ai/model-skills/list',
    save: '/api/ai/model-skills/save',
  },
} as const

export type EndpointPath = string
